### ISSUE TITLE
Connection with access key and secret does not work, but profile does

### ISSUE THREAD

**Issue by realshadow** [magJ/iam-jdbc-driver#1]
Hey,

first of all - thanks for the driver. I am using it to connect to Aurora database from Datagrip as mentioned in [this issue](https://github.com/aws/aws-toolkit-jetbrains/issues/1238). 

I have my aws cli setup so I used the `awsProfile`property and the connection worked like a charm. But when I was trying to setup the connection for my collegue who did not have cli installed, I went with `awsAccessKeyId ` and `awsSecretAccessKey`, but it always ended in `pam authentification failed` error. So I tried it on my machine with the access key and secret copied from my credentials file and the same thing happened. I even tried to encode the secret, but the error remains.

Any idea what might be the problem?

**Comment by magJ** [comment]
Make sure you are specifying a region, if it can't be picked up from a profile.  
While admittedly I hadn't previously tested usage of `awsAccessKeyId` and `awsSecretAccessKey`, it seems to work fine for me when I just tried it out.  

Below is an example of the jdbc URL I tested with:
`jdbc:iampostgresql://my-database.abcdefg.ap-southeast-2.rds.amazonaws.com/postgres?awsRegion=ap-southeast-2&awsAccessKeyId=redacted&awsSecretAccessKey=redacted`

**Comment by realshadow** [comment]
Thanks for the help. Adding region did not help, but I managed to figure it out. I had to URL encode my secret first as it contains `+` characters. Maybe loading the credentials from profile will automatically encode the secret?

I dont know why encoding did not help yesterday, but I was trying it at 2AM...

**Comment by magJ** [comment]
Ah that makes sense, yeah property passed as a URL query parameter will need to be encoded.  
Glad you got it sorted.

**Comment by realshadow** [comment]
@magJ Would mind if the encoding would be done behind the scenes automatically? For example Redshift driver from amazon does this under the hood. Although, I have no way to test it now, but did not encounter this problem before. 

I think it would be beneficial since not every user will have the tools and/or knowledge to do this.

**Comment by magJ** [comment]
Not sure what you mean, how would that work?
Say you have an access key with an ampersand in it(dunno if possible), how
would we determine that it's part of the key and not a marker for the next
parameter?
I could possibly implement a non standard url decoding algorithm that
ignores symbols like +, but then what if another user then correctly
encodes their url, it would break for them.

**Comment by realshadow** [comment]
I have added few debug statements in the driver to see what is the difference between using profile and access key with secret and it turns out, its the other way around...

According to [this](https://summitroute.com/blog/2018/06/20/aws_security_credential_formats/) (and few other sources), access key can contain only `+` or `/` as special characters. When we supply access key and secret it falls in `parseQueryString` method which uses `URLDecoder` to decode the query string. URLDecoder is generally used for HTML decoding which means it will replace `+` or `%20` with an empty space, but RFC2396 allows `+` in URI schemas. So as a simple workaround we can just replace `+` with its encoded counterpart `%2B` before we decode it. This is also the most common solution I found on stackoverflow.

If you dont mind I will create a PR with the fix

**Comment by magJ** [comment]
I have merged the change, and refactored it slightly.  
I realised that conversion of `+` to space is behavior for handling `application/x-www-form-urlencoded` URL's, which is beyond the scope of RFC 3986.  
A new release should be deployed shortly.
